//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/GameInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInputs"",
    ""maps"": [
        {
            ""name"": ""Entities"",
            ""id"": ""ec6ada94-8152-4f10-a9b2-43ed64b711dc"",
            ""actions"": [
                {
                    ""name"": ""Speed"",
                    ""type"": ""Value"",
                    ""id"": ""66d77813-00f7-4adb-8991-861c0a26e919"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Heading"",
                    ""type"": ""Button"",
                    ""id"": ""41f804a4-fc86-4150-bc55-563ccf23bf12"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextEntity"",
                    ""type"": ""Button"",
                    ""id"": ""3b552cf2-915d-4664-a091-8cdfdd4e1c09"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cursor"",
                    ""type"": ""Button"",
                    ""id"": ""42a7fd8a-c849-4703-8d52-4eef2bf49034"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CursorPosition"",
                    ""type"": ""Value"",
                    ""id"": ""7b0924d5-e41b-41d9-9f1a-9bff3cd167a6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ClearSelection"",
                    ""type"": ""Button"",
                    ""id"": ""ee26c25b-3511-4352-a334-c259731fe8c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""0217ed2a-6e62-47db-89c1-992ce1eebddf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Intercept"",
                    ""type"": ""Button"",
                    ""id"": ""f965f433-ee4c-427b-9cd2-7258f9c92b74"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Create100"",
                    ""type"": ""Button"",
                    ""id"": ""2fa46691-b915-4755-8db5-7aba03303154"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""96ec8e28-58cb-4d05-98b0-87da4816747c"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Speed"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""21efad6b-f1e3-4b7a-a79a-40bc0fe2a0c3"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Speed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""153a734f-6a93-460c-9c4b-9f492fb37ec0"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Speed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""0f0dc2a2-ba42-4860-a8e9-6397bfaffa62"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heading"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""617655b5-b928-4a4c-a34b-8dd3a1bff474"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heading"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""b414ad96-478e-426f-b776-573ccdbe74ba"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heading"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""55fb26fc-e8cd-4562-a2bf-4468583d07a0"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextEntity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13628817-c1e8-4c41-a9ab-f6605ec24f2c"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": ""SlowTap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6700d5f-b843-402e-bdf6-7d8792c01cdd"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4dd00825-988c-4e13-942c-bd4ffcd1fec5"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CursorPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e489a64c-0636-4db3-80c5-b87ec1008256"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CursorPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f04ef024-ae4b-4087-b7c3-11f44cb6feb1"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClearSelection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2dfa1597-c52e-47bd-bcab-4cd9b2548a03"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f3b0c43-0d06-477a-8db9-0c02948f316f"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": ""MultiTap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7de1f10-b7d0-4a1d-b982-7077d2aa5609"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Intercept"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c73005a-f2bd-4d92-b684-be930de06f0a"",
                    ""path"": ""<Keyboard>/f12"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Create100"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Entities
        m_Entities = asset.FindActionMap("Entities", throwIfNotFound: true);
        m_Entities_Speed = m_Entities.FindAction("Speed", throwIfNotFound: true);
        m_Entities_Heading = m_Entities.FindAction("Heading", throwIfNotFound: true);
        m_Entities_NextEntity = m_Entities.FindAction("NextEntity", throwIfNotFound: true);
        m_Entities_Cursor = m_Entities.FindAction("Cursor", throwIfNotFound: true);
        m_Entities_CursorPosition = m_Entities.FindAction("CursorPosition", throwIfNotFound: true);
        m_Entities_ClearSelection = m_Entities.FindAction("ClearSelection", throwIfNotFound: true);
        m_Entities_Move = m_Entities.FindAction("Move", throwIfNotFound: true);
        m_Entities_Intercept = m_Entities.FindAction("Intercept", throwIfNotFound: true);
        m_Entities_Create100 = m_Entities.FindAction("Create100", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Entities
    private readonly InputActionMap m_Entities;
    private List<IEntitiesActions> m_EntitiesActionsCallbackInterfaces = new List<IEntitiesActions>();
    private readonly InputAction m_Entities_Speed;
    private readonly InputAction m_Entities_Heading;
    private readonly InputAction m_Entities_NextEntity;
    private readonly InputAction m_Entities_Cursor;
    private readonly InputAction m_Entities_CursorPosition;
    private readonly InputAction m_Entities_ClearSelection;
    private readonly InputAction m_Entities_Move;
    private readonly InputAction m_Entities_Intercept;
    private readonly InputAction m_Entities_Create100;
    public struct EntitiesActions
    {
        private @GameInputs m_Wrapper;
        public EntitiesActions(@GameInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Speed => m_Wrapper.m_Entities_Speed;
        public InputAction @Heading => m_Wrapper.m_Entities_Heading;
        public InputAction @NextEntity => m_Wrapper.m_Entities_NextEntity;
        public InputAction @Cursor => m_Wrapper.m_Entities_Cursor;
        public InputAction @CursorPosition => m_Wrapper.m_Entities_CursorPosition;
        public InputAction @ClearSelection => m_Wrapper.m_Entities_ClearSelection;
        public InputAction @Move => m_Wrapper.m_Entities_Move;
        public InputAction @Intercept => m_Wrapper.m_Entities_Intercept;
        public InputAction @Create100 => m_Wrapper.m_Entities_Create100;
        public InputActionMap Get() { return m_Wrapper.m_Entities; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(EntitiesActions set) { return set.Get(); }
        public void AddCallbacks(IEntitiesActions instance)
        {
            if (instance == null || m_Wrapper.m_EntitiesActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_EntitiesActionsCallbackInterfaces.Add(instance);
            @Speed.started += instance.OnSpeed;
            @Speed.performed += instance.OnSpeed;
            @Speed.canceled += instance.OnSpeed;
            @Heading.started += instance.OnHeading;
            @Heading.performed += instance.OnHeading;
            @Heading.canceled += instance.OnHeading;
            @NextEntity.started += instance.OnNextEntity;
            @NextEntity.performed += instance.OnNextEntity;
            @NextEntity.canceled += instance.OnNextEntity;
            @Cursor.started += instance.OnCursor;
            @Cursor.performed += instance.OnCursor;
            @Cursor.canceled += instance.OnCursor;
            @CursorPosition.started += instance.OnCursorPosition;
            @CursorPosition.performed += instance.OnCursorPosition;
            @CursorPosition.canceled += instance.OnCursorPosition;
            @ClearSelection.started += instance.OnClearSelection;
            @ClearSelection.performed += instance.OnClearSelection;
            @ClearSelection.canceled += instance.OnClearSelection;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Intercept.started += instance.OnIntercept;
            @Intercept.performed += instance.OnIntercept;
            @Intercept.canceled += instance.OnIntercept;
            @Create100.started += instance.OnCreate100;
            @Create100.performed += instance.OnCreate100;
            @Create100.canceled += instance.OnCreate100;
        }

        private void UnregisterCallbacks(IEntitiesActions instance)
        {
            @Speed.started -= instance.OnSpeed;
            @Speed.performed -= instance.OnSpeed;
            @Speed.canceled -= instance.OnSpeed;
            @Heading.started -= instance.OnHeading;
            @Heading.performed -= instance.OnHeading;
            @Heading.canceled -= instance.OnHeading;
            @NextEntity.started -= instance.OnNextEntity;
            @NextEntity.performed -= instance.OnNextEntity;
            @NextEntity.canceled -= instance.OnNextEntity;
            @Cursor.started -= instance.OnCursor;
            @Cursor.performed -= instance.OnCursor;
            @Cursor.canceled -= instance.OnCursor;
            @CursorPosition.started -= instance.OnCursorPosition;
            @CursorPosition.performed -= instance.OnCursorPosition;
            @CursorPosition.canceled -= instance.OnCursorPosition;
            @ClearSelection.started -= instance.OnClearSelection;
            @ClearSelection.performed -= instance.OnClearSelection;
            @ClearSelection.canceled -= instance.OnClearSelection;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Intercept.started -= instance.OnIntercept;
            @Intercept.performed -= instance.OnIntercept;
            @Intercept.canceled -= instance.OnIntercept;
            @Create100.started -= instance.OnCreate100;
            @Create100.performed -= instance.OnCreate100;
            @Create100.canceled -= instance.OnCreate100;
        }

        public void RemoveCallbacks(IEntitiesActions instance)
        {
            if (m_Wrapper.m_EntitiesActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IEntitiesActions instance)
        {
            foreach (var item in m_Wrapper.m_EntitiesActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_EntitiesActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public EntitiesActions @Entities => new EntitiesActions(this);
    public interface IEntitiesActions
    {
        void OnSpeed(InputAction.CallbackContext context);
        void OnHeading(InputAction.CallbackContext context);
        void OnNextEntity(InputAction.CallbackContext context);
        void OnCursor(InputAction.CallbackContext context);
        void OnCursorPosition(InputAction.CallbackContext context);
        void OnClearSelection(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnIntercept(InputAction.CallbackContext context);
        void OnCreate100(InputAction.CallbackContext context);
    }
}
